import { List } from 'immutable'
import PropTypes from 'prop-types'

// const

export const promotionConstants = {
    addRemainingHeadCells: [
        { id: 'created_by', label: 'Created By', draggable: true, width: '14%' },
        { id: 'updated_by', label: 'Updated By', draggable: true, width: '14%' },
        { id: 'created', label: 'Created At', draggable: true, width: '14%' },
        { id: 'updated', label: 'Updated At', draggable: true, width: '14%' },
    ],
    contentFilters: [
        { key: 'state', label: 'Region', after: 'comma' },
        { key: 'placement_location', label: 'Placement', after: 'comma' },
        { key: 'status', label: 'Status', after: 'comma' },
    ],
    placements: ['Homepage Carousel', 'Deal Tile'],
    statusFields: ['live', 'finished', 'scheduled', 'incomplete'],
    contentStatus: ['Complete', 'Incomplete'],
    qaStatusFields: ['In QA Testing', 'Not In QA Testing'],
    manageContentHeadCells: [
        { id: 'app', label: 'App', width: '10%', sortable: true },
        { id: 'placement_location', label: 'Placement', width: '12%', sortable: true },
        { id: 'region', label: 'Region', width: '12%', sortable: true },
        { id: 'image', label: 'Image Upload', width: '20%' },
        { id: 'timeInterval', label: 'Time Interval', width: '16%' },
        { id: 'status', label: 'Status', width: '12%', sortable: true },
        { id: 'actions', label: 'Actions', width: '12%', align: 'left' },
    ],
    marketingStatusFields: ['complete', 'incomplete'],
    marketingSteps: [
        { step: 0, name: 'placements', title: 'App Placements', value: 'app' },
        { step: 1, name: 'schedule', title: 'Schedule', value: 'start_date' },
        { step: 2, name: 'audience', title: 'Audience', value: 'region' },
        { step: 3, name: 'prioritization', title: 'Prioritization', value: 'priority' },
        { step: 4, name: 'manageContent', title: 'Manage Content', value: 'msg_input' },
    ],
    prioritizeContentHeadCells: [
        { id: 'radio', width: '5%' },
        { id: 'tier', label: 'Tier', width: '7%' },
        { id: 'category', label: 'Category', width: '16.66%' },
    ],
    prioritizationCategoriesList: [
        { id: 'free_LTO', label: 'Any FREE or LTO Offer', tier: 1 },
        { id: 'alcohol', label: 'Alcohol', tier: 2 },
        { id: 'freshFoods', label: 'Fresh Foods', tier: 3 },
        { id: 'drinks_iceCream', label: 'Drinks, Ice Cream', tier: 4 },
        { id: 'candy', label: 'Candy', tier: 5 },
        { id: 'other', label: 'Other', tier: 6 },
    ],
    manageContentFilter: List([
        {
            type: 'list',
            key: 'placement_location',
            display_name: 'Placement',
            display_value: [],
            post_value: [],
        },
        {
            type: 'list',
            key: 'region',
            display_name: 'Region',
            display_value: [],
            post_value: [],
        },
        {
            type: 'list',
            key: 'status',
            display_name: 'Status',
            display_value: [],
            post_value: [],
        },
    ]),
    promotionFilterLabels: [
        { key: 'name', label: 'Search' },
        { key: 'createdBy', label: 'Created By', after: 'comma' },
        { key: 'lastModifiedBy', label: 'Last Modified', after: 'comma' },
        { key: 'promoSlin', label: 'Promo Slin', after: 'comma' },
        { key: 'marketingStatus', label: 'Marketing Status', after: 'comma' },
        { key: 'publishedStatus', label: 'Published Status', after: 'comma' },
        { key: 'date_range', label: 'Date Range', after: 'hyphen' },
    ],
    promotionModules: ['marketing'],
    promotionsHeadCells: [
        { id: 'name', label: 'Content Title', draggable: false, width: '13%' },
        { id: 'show_at', label: 'Placements', draggable: true, width: '13%' },
        { id: 'start_date', label: 'Date', draggable: true, width: '12%', sortable: true },
        { id: 'state', label: 'Audience', draggable: true, width: '10%' },
        { id: 'priority', label: 'Priority', draggable: true, width: '7%' },
        { id: 'status', label: 'Status', draggable: true, width: '10%', sortable: true },
        { id: 'qa_is_live', label: 'QA Testing', draggable: true, width: '8%', sortable: true },
        { id: 'is_live', label: 'Prod', draggable: true, width: '6%', sortable: true },
        { id: 'action', label: 'Action', draggable: false, width: '4%' },
    ],
    promoConfigPropType: PropTypes.arrayOf(
        PropTypes.shape({
            excludes: PropTypes.arrayOf(PropTypes.string),
            status: PropTypes.string,
            id: PropTypes.string,
            app: PropTypes.string,
            placement_location: PropTypes.string,
            region: PropTypes.string,
            copy: PropTypes.string,
            legal_disclaimer: PropTypes.string,
            landing_page_name: PropTypes.string,
            landing_page_type: PropTypes.string,
            landing_page_id: PropTypes.string,
            image_url: PropTypes.string,
        })
    ),
    promoPropType: PropTypes.shape({
        _id: PropTypes.string,
        name: PropTypes.string,
        is_live: PropTypes.bool,
        qa_is_live: PropTypes.bool,
        status: PropTypes.string,
        configurations: PropTypes.arrayOf(
            PropTypes.shape({
                excludes: PropTypes.arrayOf(PropTypes.string),
                status: PropTypes.string,
                id: PropTypes.string,
                app: PropTypes.string,
                placement_location: PropTypes.string,
                region: PropTypes.string,
                copy: PropTypes.string,
                legal_disclaimer: PropTypes.string,
                landing_page_name: PropTypes.string,
                landing_page_type: PropTypes.string,
                landing_page_id: PropTypes.string,
                image_url: PropTypes.string,
            })
        ),
        schedule: PropTypes.object,
        created_by: PropTypes.string,
        created: PropTypes.string,
        updated_by: PropTypes.string,
        updated: PropTypes.string,
        type: PropTypes.arrayOf(PropTypes.string),
    }),
    publishedStatusFields: ['Published', 'Unpublished'],
    sevenAppPlacementTiles: [
        { name: 'Homepage Carousel', title: 'HOMEPAGE CAROUSEL', width: 2058, height: 1020 },
        { name: 'Deal Tile', title: 'DEAL TILE', width: 2058, height: 1020 },
    ],
    publishStatusMap: {
        Published: true,
        Unpublished: false,
    },
    publishQAStatusMap: {
        In_QA_Testing: true,
        Not_In_QA_Testing: false,
    },
    publishContentAction: {
        qa_live: 'QA Testing',
        live: 'Publish to Production',
    },
    publishContentStatus: {
        true: 'enabled',
        false: 'disabled',
    },
    statesList: {
        AL: 'Alabama',
        AK: 'Alaska',
        AZ: 'Arizona',
        AR: 'Arkansas',
        CA: 'California',
        CO: 'Colorado',
        CT: 'Connecticut',
        DC: 'District of Columbia',
        DE: 'Delaware',
        FL: 'Florida',
        GA: 'Georgia',
        HI: 'Hawaii',
        ID: 'Idaho',
        IL: 'Illinois',
        IN: 'Indiana',
        IA: 'Iowa',
        KS: 'Kansas',
        KY: 'Kentucky',
        LA: 'Louisiana',
        ME: 'Maine',
        MD: 'Maryland',
        MA: 'Massachusetts',
        MI: 'Michigan',
        MN: 'Minnesota',
        MS: 'Mississippi',
        MO: 'Missouri',
        MT: 'Montana',
        NE: 'Nebraska',
        NV: 'Nevada',
        NH: 'New Hampshire',
        NJ: 'New Jersey',
        NM: 'New Mexico',
        NY: 'New York',
        NC: 'North Carolina',
        ND: 'North Dakota',
        OH: 'Ohio',
        OK: 'Oklahoma',
        OR: 'Oregon',
        PA: 'Pennsylvania',
        PR: 'Puerto Rico',
        RI: 'Rhode Island',
        SC: 'South Carolina',
        SD: 'South Dakota',
        TN: 'Tennessee',
        TX: 'Texas',
        UT: 'Utah',
        VT: 'Vermont',
        VA: 'Virginia',
        WA: 'Washington',
        WV: 'West Virginia',
        WI: 'Wisconsin',
        WY: 'Wyoming',
    },
}
